name: issue
on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
env:
  AWS_REGION: us-east-1
jobs:
  issue:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      issues: write
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          aws bedrock-agent-runtime retrieve-and-generate \
            --retrieve-and-generate-configuration 'type=KNOWLEDGE_BASE,knowledgeBaseConfiguration={knowledgeBaseId=${{ secrets.KNOWLEDGE_BASE_ID }},modelArn=${{ secrets.MODEL_ARN }}}' \
            --input 'text=${{ github.event_name == 'issues' && format(fromJSON('"# {0}\n{1}"'), github.event.issue.title, github.event.issue.body) || github.event.comment.body }}' \
            | jq -r '.citations | map(.generatedResponsePart.textResponsePart.text) | join("\n")' \
            | gh issue comment ${{ github.event.issue.number }} -R ${{ github.repository }} -F -
