name: sync
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
env:
  AWS_REGION: us-east-1
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          aws s3 sync . s3://${{ secrets.DATA_SOURCE_BUCKET_NAME }} \
            --exclude '.git/*' \
            --exact-timestamps \
            --delete
      - run: |
          aws bedrock-agent start-ingestion-job \
            --knowledge-base-id ${{ secrets.KNOWLEDGE_BASE_ID }} \
            --data-source-id ${{ secrets.DATA_SOURCE_ID }}
